### ISSUE TITLE
[Docs]: There should be a document that is used as a guide when setting up new repos from the template

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/oss-repo-template-golang#34]
### What page needs improvement?

Link a UR

### Description

When creating a new repo from this template, there are a few things that need to be adjusted in order for CI to work properly. Additionally, when you create a new repo from a template, only the contents of the template repo are copied over, not all of the repo settings. Therefore, after creating a new repo, you will need to manually configure the settings. There are also a handful of files that will need to be deleted.

### Remedy

We should have a document that serves as a guide or checklist that is used when setting up new repos from this template. This new document would outline the various things that need to be changed/adjusted to ensure everything works properly in the new repo, that the appropriate settings are configured, and that unnecessary files are deleted.

Things that should be included:
- [x] What changes are needed in all of the CI workflow yaml files. This is easier than having to read through each yaml file to figure out what changes are needed.
- [x] Link to the settings document that specifies which settings should be configured on the repo.
- [x] Point out which files can safely be deleted e.g. `go.mod`, `go.sum`, `interchain_test.go`, `main.go`, `SETTINGS.md`, etc.
- [ ] Any other steps that are necessary to have a clean repo that is derived from this template

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joelsmith-2019** [comment]
Please see PR #39 and let me know if any changes should be made.
