### ISSUE TITLE
[Docs]: fix broken link to GitHub security advisory reporting

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/oss-repo-template-golang#40]
### What page needs improvement?

https://github.com/strangelove-ventures/oss-repo-template-golang/blob/main/SECURITY.md?plain=1#L5

### Description

The link to the GitHub security advisory reporting is broken because we are attempting to use relative paths to this webpage but relative paths only work if we are linking to a document that is in the repo. This will need to be an explicit link to the webpage and would need to be change on every repo so that it links to the correct web page for that repo

### Remedy

We would need to either link explicitly to the web page, which would require changing the link in the `SECURITY.md` file in every repo. To avoid having to make this change in every repo we upload the file to we may consider not linking to the page but just providing instruction on how to access the page. 

Thoughts??? @beckettsean 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beckettsean** [comment]
We should link to the GH help about private reporting: 

https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability#privately-reporting-a-security-vulnerability
